"""Initial migration

Revision ID: 26a8e7e55378
Revises: 
Create Date: 2024-11-13 16:23:11.342683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8e7e55378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('korisnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('korisnicko_ime', sa.String(length=50), nullable=False),
    sa.Column('lozinka', sa.String(length=100), nullable=False),
    sa.Column('grad', sa.String(length=50), nullable=True),
    sa.Column('drzava', sa.String(length=50), nullable=True),
    sa.Column('broj_telefona', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('korisnicko_ime')
    )
    op.create_table('teme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv')
    )
    op.create_table('diskusije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naslov', sa.String(length=150), nullable=False),
    sa.Column('tekst', sa.Text(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['korisnici.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['teme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komentari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tekst', sa.Text(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('diskusija_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['korisnici.id'], ),
    sa.ForeignKeyConstraint(['diskusija_id'], ['diskusije.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('komentari')
    op.drop_table('diskusije')
    op.drop_table('teme')
    op.drop_table('korisnici')
    # ### end Alembic commands ###
