"""Povecana duzina lozinke na 255

Revision ID: 4f8bd840ca65
Revises: 26a8e7e55378
Create Date: 2024-11-13 19:48:57.892220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8bd840ca65'
down_revision = '26a8e7e55378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('korisnici', schema=None) as batch_op:
        batch_op.alter_column('lozinka',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('korisnici', schema=None) as batch_op:
        batch_op.alter_column('lozinka',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
