"""added is_first_login field

Revision ID: 833727f53361
Revises: f62d387d7f79
Create Date: 2024-11-21 14:04:27.746796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833727f53361'
down_revision = 'f62d387d7f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_first_login')

    # ### end Alembic commands ###
