"""added is_first_login field

Revision ID: b70b0b5dc1f5
Revises: 833727f53361
Create Date: 2024-11-21 14:04:44.038496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70b0b5dc1f5'
down_revision = '833727f53361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
